# wrangler.toml (wrangler v4.0.0^)
name = "submit"
main = "functions/api/submit.js"
compatibility_date = "2022-12-05"
compatibility_flags = [ "nodejs_compat_v2" ]

[assets]
directory = "_site"
not_found_handling = "404-page"

[observability.logs]
enabled = true
