# wrangler.toml (wrangler v4.0.0^)
name = "submit"
main = "functions/api/submit.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2026-02-04"

[assets]
directory = "_site"
not_found_handling = "404-page"

[observability.logs]
enabled = true
